spring:
  #?????
  datasource:
    url: jdbc:mysql://47.97.208.219:3306/zuo?serverTimezone=Asia/Shanghai&useSSL=false
    username: zuo
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #jackson??
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

    #???
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: WEB-INF/**

  #redis??
  redis:
    host: 47.97.208.219
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

#mybatis??
mybatis-plus:
  type-aliases-package: com.zuo.entity
  mapper-locations: classpath:mapper/*.xml

#????
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR

#??????
server:
  port: 8087





